### ISSUE TITLE
Extract alliance tag and channel id to own config file

### ISSUE THREAD

**Issue by TheAlexLichter** [LordFrz/AlbionKillBot#1]
Hey!

As you wrote in your readme file, whoever wants to host the bot should change the content of the .js file to setup his alliance tag and channel id. 

It'd be better to extract those info to an own config.json (call it whatever you like to), which is way "cleaner".

E.g. people can still use `git pull` to get newer version of your bot without merge conflicts.

**Comment by LordFrz** [comment]
Thanks, that something I will do either later today or tomorrow.
