### ISSUE TITLE
ES6 Style

### ISSUE THREAD

**Issue by TheAlexLichter** [LordFrz/AlbionKillBot#2]
I'd suggest that you (re-)write your bot at least partly in ES6 style
You don't need to use the new import type and can stick with require() (node.js doesn't support it by default currently), but please use *const* and *let* instead of var! 🙏 

Related: https://www.codementor.io/iykyvic/writing-your-nodejs-apps-using-es6-6dh0edw2o

**Comment by LordFrz** [comment]
I will look into it, thanks.
